### ISSUE TITLE
Incorrect status on `gap`

### ISSUE THREAD

**Issue by octref** [mdn/data#213]
I found the following entry in `properties.json`

```json
  "gap": {
    "syntax": "<'row-gap'> <'column-gap'>?",
    "media": "visual",
    "inherited": false,
    "animationType": [
      "row-gap",
      "column-gap"
    ],
    "percentages": "no",
    "groups": [
      "CSS Box Alignment"
    ],
    "initial": [
      "row-gap",
      "column-gap"
    ],
    "appliesto": "gridContainers",
    "computed": [
      "row-gap",
      "column-gap"
    ],
    "order": "uniqueOrder",
    "status": "standard"
  },
```

However, there is no MDN page that corresponds to it.

I think this might be a non-standard property pre `grid-gap`. I think it should be either removed or marked as non-standard with a dedicating MDN page.

**Comment by wbamberg** [comment]
I think it might be the other way round: `grid-gap` was the old name and it is now named `gap`, since it's now part of the box-alignment spec and is not specific to Grid:

https://www.w3.org/TR/css-align-3/#gap-shorthand
https://www.w3.org/TR/css-align-3/#gap-legacy

So I think the data here is correct, and the MDN `grid-gap` page should be renamed `gap`, with the legacy usage noted.

**Comment by octref** [comment]
I wasn't aware of the renaming from `grid-gap` to `gap`. The data is indeed correct. Thanks for your clarification!

> So I think the data here is correct, and the MDN grid-gap page should be renamed gap, with the legacy usage noted.

Sounds great. I don't think I can contribute to that change, so would you mind closing this issue when that page becomes available?
Additionally `grid-gap` should redirect to `gap`, probably.

**Comment by wbamberg** [comment]
I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1456563, it should be tracked there so I'm closing this one.
