### ISSUE TITLE
Need inheritance data for Web Authentication API

### ISSUE THREAD

**Issue by jpmedley** [mdn/data#337]
The inheritance for these APIs looks like this.

`AuthenticatorResponse`
`  `[`AuthenticatorAttestationResponse`](https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/credentialmanager/authenticator_attestation_response.idl)
`   `[`AuthenticatorAssertionResponse`](https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/credentialmanager/authenticator_assertion_response.idl)

**Comment by chrisdavidmills** [comment]
I think we need to record inheritance data in https://github.com/mdn/kumascript/blob/master/macros/InterfaceData.json rather than here, as that's the data that MDN actually uses. It is obviously foolish to record it in two places.

See https://github.com/mdn/data/pull/303 for the latest time we discussed this.

@Elchi3, pinging you too, to make sure I'm correct here.

**Comment by Elchi3** [comment]
I think you are correct about this and yes, it's foolish.

**Comment by chrisdavidmills** [comment]
OK, cool. So @jpmedley , are you OK to close this issue and submit the data over in the KumaScript repo?

**Comment by jpmedley** [comment]
Yes. I'm allowed to contribute to kumascript.

**Comment by chrisdavidmills** [comment]
Cool.
